// This file is a placeholder.
// The actual Service Worker is generated by vite-plugin-pwa during the build process.
// See vite.config.ts for configuration.
console.log('Manual sw.js is deprecated. Vite PWA plugin handles service worker generation.');